#!/bin/bash

### BEGIN INIT INFO
# Provides:
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: hobot hdmi init
# Description:
### END INIT INFO

f=$(tr -d '\0' </sys/firmware/devicetree/base/chosen/bootargs)
ko_root="/lib/modules/4.14.87"
#echo $f
cm480p="cm480p"
lcd="video=hobot:lcd"
m720p="video=hobot:720p"
x3sdb_mipi720p="video=hobot:x3sdb-mipi720p"
m1080p="video=hobot:1080p"
hdmi="video=hobot:hdmi"
x3sdb_hdmi1080p="video=hobot:x3sdb-hdmi"
bt656="video=hobot:bt656"
video="video=hobot"
res=`/usr/bin/get_hdmi_res | awk -F ',' '{print $1}'`
echo "Display resolution: $res"
rbt656=$(echo $f | grep "${bt656}")
if [[ "$rbt656" != "" ]]
then
  echo "display panel is BT656 panel"
  echo bt656 > /sys/devices/virtual/graphics/iar_cdev/iar_test_attr
  if [ -f "/etc/iar/iar_xj3_bt656.json" ]
  then
    /usr/bin/x3dispinit /etc/iar/iar_xj3_bt656.json
    echo start > /sys/devices/virtual/graphics/iar_cdev/iar_test_attr
  else
    echo "no bt656 configuration file, use default config"
  fi
fi

rhdmi=$(echo $f | grep "${x3sdb_hdmi1080p}")
if [[ "$rhdmi" != "" ]]
then
  echo "Display panel is HDMI-1080P"
  if [ -f "/etc/iar/iar_x3sdb_hdmi_1080p.json" ]
  then
    /usr/bin/x3dispinit "/etc/iar/iar_x3sdb_hdmi_${res}p.json" &
    echo start > /sys/devices/virtual/graphics/iar_cdev/iar_test_attr
    echo disable0 > /sys/devices/virtual/graphics/iar_cdev/iar_test_attr
  else
    echo "Hdmi 1080p configuration file not found, use default config"
  fi
fi

rhdmi=$(echo $f | grep "${hdmi}")
if [[ "$rhdmi" != "" ]]
then
  echo "display panel is HDMI"
  if [ -f "/etc/iar/iar_xj3_hdmi_1080p.json" ]
  then
    /usr/bin/x3dispinit /etc/iar/iar_xj3_hdmi_1080p.json
    echo start > /sys/devices/virtual/graphics/iar_cdev/iar_test_attr
  else
    echo "no hdmi configuration file, use default config"
  fi
fi


result=$(echo $f | grep "${m720p}")
if [[ "$result" != "" ]]
then
  echo "display panel is MIPI-720P"
  echo dsi720p > /sys/devices/virtual/graphics/iar_cdev/iar_test_attr
  if [ -f "/etc/iar/iar_xj3_mipi720p.json" ]
  then
    /usr/bin/x3dispinit /etc/iar/iar_xj3_mipi720p.json
    echo start > /sys/devices/virtual/graphics/iar_cdev/iar_test_attr
  else
    echo "no mipi720p configuration file, use 720p default config"
  fi
fi

result0=$(echo $f | grep "${lcd}")
if [[ "$result0" != "" ]]
then
  echo "display panel is 7inch LCD"
  echo lcd > /sys/devices/virtual/graphics/iar_cdev/iar_test_attr
  if [ -f "/etc/iar/iar_xj3_lcd.json" ]
  then
    /usr/bin/x3dispinit /etc/iar/iar_xj3_lcd.json
    echo start > /sys/devices/virtual/graphics/iar_cdev/iar_test_attr
  else
    echo "no LCD configuration file, use LCD default config"
  fi
fi

result1=$(echo $f | grep "${m1080p}")
if [[ "$result1" != "" ]]
then
  echo "display panel is MIPI-1080P"
  echo dsi1080 > /sys/devices/virtual/graphics/iar_cdev/iar_test_attr
  if [ -f "/etc/iar/iar_xj3_mipi1080p.json" ]
  then
    /usr/bin/x3dispinit /etc/iar/iar_xj3_mipi1080p.json
    echo start > /sys/devices/virtual/graphics/iar_cdev/iar_test_attr
  else
    echo "no mipi1080p configuration file, use 1080p default config"
  fi
fi

result2=$(echo $f | grep "${x3sdb_mipi720p}")
if [[ "$result2" != "" ]]
then
  echo "display panel is MIPI-720P Portrait"
  som_name=$(cat /sys/class/socinfo/som_name)
  if [ ${som_name} == '5' ] || [ ${som_name} == '6' ];then
    # reset LCD
    echo 61 > /sys/class/gpio/export
    echo out > /sys/class/gpio/gpio61/direction
    echo 1 > /sys/class/gpio/gpio61/value
    echo 61 > /sys/class/gpio/unexport

    # Enable backlight
    echo 62 > /sys/class/gpio/export
    echo out > /sys/class/gpio/gpio62/direction
    echo 1 > /sys/class/gpio/gpio62/value
    echo 62 > /sys/class/gpio/unexport
  elif [ ${som_name} == '3' ]  || [ ${som_name} == '4' ]; then
    # Rest LCD
    echo 117 > /sys/class/gpio/export
    echo out > /sys/class/gpio/gpio117/direction
    echo 1 > /sys/class/gpio/gpio117/value
    echo 117 > /sys/class/gpio/unexport
    # Enable backlight
    echo 22 > /sys/class/gpio/export
    echo out > /sys/class/gpio/gpio22/direction
    echo 1 > /sys/class/gpio/gpio22/value
    echo 22 > /sys/class/gpio/unexport
  fi
  if [ -f "/etc/iar/iar_xj3_mipi720p.json" ]
  then
    /usr/bin/x3dispinit /etc/iar/iar_xj3_mipi720p.json &
    echo dsi720x1280 > /sys/devices/virtual/graphics/iar_cdev/iar_test_attr
    echo disable0 > /sys/devices/virtual/graphics/iar_cdev/iar_test_attr
  else
    echo "no mipi 720p configuration file for 720p portraint, use 1080p default config"
  fi
fi
result2=$(echo $f | grep "${cm480p}")
if [[ "$result2" != "" ]]
then
  echo "display panel is MIPI-480P Portrait"
  if [ -f "/etc/iar/iar_xj3_mipi480p.json" ]
  then
    /usr/bin/x3dispinit /etc/iar/iar_xj3_mipi480p.json &
    echo cm480p > /sys/devices/virtual/graphics/iar_cdev/iar_test_attr
    echo start > /sys/devices/virtual/graphics/iar_cdev/iar_test_attr
    echo disable0 > /sys/devices/virtual/graphics/iar_cdev/iar_test_attr
    modprobe ft5406
    modprobe hbx3_bl
  else
    echo "no mipi 480p configuration file for 480p portraint, use 1080p default config"
  fi
fi
#echo "@@@@@@disp config end@@@@@@@@@@@@"
exit 0
